"""RatingPage — Studio's post-class rating / survey screen.

Reached after ending a class (when class progressed far enough to
trigger rating). Submitting advances to SummaryPage.

Two observed variants — confirmed across class types on 2026-04-27:

  3-SECTION VARIANT — VOD classes only
    Session, Instructor, Difficulty For You

  2-SECTION VARIANT — CPS AND Workout classes
    Session, Difficulty For You
    (no Instructor section — for CPS, the trainer is the user's
    assigned personal trainer with separate feedback channels; for
    Workout / Planned Session, classes are typically Team FORME
    content where individual instructor rating may not apply)

Layout (same structure, different section count):

  text_title | "How Satisfied Are You With"   ← screen header

  recycler                                     ← list of rating sections
    [section 1 — always]
      text_title | "Session"
      layout_options                           ← 5 rating buttons
        content-desc | rating_session_star_1..5
    [section 2 — VOD only]
      text_title | "Instructor"
      layout_options
        content-desc | rating_instructor_star_1..5
    [last section — always]
      text_title | "Difficulty For You"
      layout_options
        content-desc | rating_difficulty_for_you_star_1..5

  button_submit | "SUBMIT"

STUDIO-4289 (Ready for QA on 2026-05-15):
  Dev added content-desc accessibility IDs to all 15 rating stars.
  Verified via dump_screen_attach on the fix build — all 15 stars
  carry their content-desc values as set by PostClassSurveyAdapter.

STUDIO-4263 / PostClassSurveyAdapter update (2026-05-12):
  Content-descriptions are now generated dynamically from the survey
  step title converted to snake_case via toSnakeCase():
    "rating_{step.title.toSnakeCase()}_star_{index+1}"
  Known step titles and their snake_case forms:
    "Session"          → rating_session_star_1..5
    "Instructor"       → rating_instructor_star_1..5
    "Difficulty For You" → rating_difficulty_for_you_star_1..5
  Tests MUST locate stars via content-description (AccessibilityId),
  NOT by index position inside layout_options, because the recycler
  recycles view holders across survey steps.
"""
from appium.webdriver.common.appiumby import AppiumBy
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

from surfaces.studio_android.pages.base import StudioBasePage, log


class RatingPage(StudioBasePage):
    # ------------------------------------------------------------------ #
    # Screen-level markers
    # ------------------------------------------------------------------ #
    SCREEN_HEADER_ID = "text_title"      # "How Satisfied Are You With"
    RECYCLER_ID = "recycler"
    SUBMIT_BUTTON_ID = "button_submit"

    # ------------------------------------------------------------------ #
    # Section title text values (as rendered on screen)
    # ------------------------------------------------------------------ #
    SECTION_SESSION = "Session"
    SECTION_INSTRUCTOR = "Instructor"
    SECTION_DIFFICULTY = "Difficulty For You"

    # ------------------------------------------------------------------ #
    # Star content-description patterns
    # Generated by PostClassSurveyAdapter:
    #   "rating_{step.title.toSnakeCase()}_star_{index+1}"
    # ------------------------------------------------------------------ #
    STAR_COUNT = 5

    # Session stars
    SESSION_STARS = [f"rating_session_star_{i}" for i in range(1, 6)]

    # Instructor stars (VOD only)
    INSTRUCTOR_STARS = [f"rating_instructor_star_{i}" for i in range(1, 6)]

    # Difficulty For You stars
    DIFFICULTY_STARS = [f"rating_difficulty_for_you_star_{i}" for i in range(1, 6)]

    # ------------------------------------------------------------------ #
    # Wait / navigation helpers
    # ------------------------------------------------------------------ #

    def wait_for_rating_screen(self, timeout=15):
        """Wait until the rating recycler is visible."""
        log.info("RatingPage: waiting for rating screen")
        WebDriverWait(self.driver, timeout).until(
            EC.presence_of_element_located(
                (AppiumBy.ID, f"{self.APP_PACKAGE}:id/{self.RECYCLER_ID}")
            )
        )
        log.info("RatingPage: rating screen visible")

    def is_loaded(self, timeout=10):
        """Return True if the rating screen header is visible."""
        return self.is_text_visible("How Satisfied Are You With", timeout=timeout)

    # ------------------------------------------------------------------ #
    # Section presence
    # ------------------------------------------------------------------ #

    def is_section_visible(self, section_title, timeout=5):
        """Return True if a section with the given title text is visible."""
        return self.is_text_visible(section_title, timeout=timeout)

    def is_session_section_visible(self, timeout=5):
        return self.is_section_visible(self.SECTION_SESSION, timeout=timeout)

    def is_instructor_section_visible(self, timeout=5):
        return self.is_section_visible(self.SECTION_INSTRUCTOR, timeout=timeout)

    def is_difficulty_section_visible(self, timeout=5):
        return self.is_section_visible(self.SECTION_DIFFICULTY, timeout=timeout)

    # ------------------------------------------------------------------ #
    # Star interaction — by content-description
    # ------------------------------------------------------------------ #

    def _find_star_by_content_desc(self, content_desc, timeout=5):
        """Locate a single star element by its content-description."""
        return WebDriverWait(self.driver, timeout).until(
            EC.presence_of_element_located(
                (AppiumBy.ACCESSIBILITY_ID, content_desc)
            )
        )

    def is_star_visible(self, content_desc, timeout=5):
        """Return True if a star with the given content-description is visible."""
        try:
            el = self._find_star_by_content_desc(content_desc, timeout=timeout)
            return el.is_displayed()
        except Exception:
            return False

    def tap_star(self, content_desc, timeout=5):
        """Tap a rating star identified by its content-description."""
        log.info(f"RatingPage: tapping star '{content_desc}'")
        el = self._find_star_by_content_desc(content_desc, timeout=timeout)
        el.click()

    # ------------------------------------------------------------------ #
    # Convenience helpers — tap a named rating in a given section
    # ------------------------------------------------------------------ #

    def tap_session_star(self, star_index):
        """Tap a Session star. star_index is 1-based (1=worst, 5=best)."""
        assert 1 <= star_index <= self.STAR_COUNT
        self.tap_star(self.SESSION_STARS[star_index - 1])

    def tap_instructor_star(self, star_index):
        """Tap an Instructor star (VOD only). star_index is 1-based."""
        assert 1 <= star_index <= self.STAR_COUNT
        self.tap_star(self.INSTRUCTOR_STARS[star_index - 1])

    def tap_difficulty_star(self, star_index):
        """Tap a Difficulty For You star. star_index is 1-based."""
        assert 1 <= star_index <= self.STAR_COUNT
        self.tap_star(self.DIFFICULTY_STARS[star_index - 1])

    def all_session_stars_visible(self, timeout=5):
        """Return True if all 5 Session stars are visible."""
        return all(self.is_star_visible(cd, timeout=timeout) for cd in self.SESSION_STARS)

    def all_instructor_stars_visible(self, timeout=5):
        """Return True if all 5 Instructor stars are visible."""
        return all(self.is_star_visible(cd, timeout=timeout) for cd in self.INSTRUCTOR_STARS)

    def all_difficulty_stars_visible(self, timeout=5):
        """Return True if all 5 Difficulty For You stars are visible."""
        return all(self.is_star_visible(cd, timeout=timeout) for cd in self.DIFFICULTY_STARS)

    # ------------------------------------------------------------------ #
    # Submit
    # ------------------------------------------------------------------ #

    def tap_submit(self, timeout=10):
        """Tap the SUBMIT button to submit the rating."""
        log.info("RatingPage: tapping SUBMIT")
        self.tap_by_id(self.SUBMIT_BUTTON_ID, timeout=timeout)
